### PR TITLE
first pass at using pytest with consistent parallel coverage

### PR DESCRIPTION
**Pull request by nickhand**
This is a very similar framework that relies on pytest under the hood and treats coverage properly in parallel.

* `runtests.py` inherits all of the command-line arguments of the `pytest` command, with the additional ones references MPI, building, and coverage

Thoughts, @rainwoodman ?

### CODE REVIEW

**Comment by nickhand** [comment]
If we decide to use pytest, the obvious name change would simply be `mpi4pytest`

**Comment by rainwoodman** [comment]
The travis error is concerning; looks like the Python path tricks were not in effect?
```
 ERROR collecting build/testenv/lib/python3.5/site-packages/mpi4py_test/tests/test_uncollective.py 

import file mismatch:

imported module 'mpi4py_test.tests.test_uncollective' has this __file__ attribute:

  /home/travis/build/rainwoodman/mpi4py_test/mpi4py_test/tests/test_uncollective.py

which is not the same as the test file we want to collect:

  /home/travis/build/rainwoodman/mpi4py_test/build/testenv/lib/python3.5/site-packages/mpi4py_test/tests/test_uncollective.py

HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules

!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
```

**Comment by rainwoodman** [comment]
I sort of recalled this is unavoidable in mpi4pytest itself. See if wrapping sys.path.remove('.') around the test module import helps?

**Comment by nickhand** [comment]
yeah we run into issues because we are importing the thing we are trying to test in `runtests.py`. I think you can get around this issue if you don't build the package first. I've been testing on nbodykit and everything has been working well

**Comment by rainwoodman** [comment]
The issue only occurs when you need to build a package. I added a few commits to a new PR #2 . Let's move there.

**Pull request closed without merging**
